package:
  name: chl26predictor 
  version: "1.1"

source:
  fn: 1.1.tar.gz
  url: https://github.com/LCR-BCCRC/CHL26predictor/archive/1.1.tar.gz

build:
  build: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base >=3.1.2
    - r-nanostringnorm

  run:
    - r-base >=3.1.2
    - r-nanostringnorm

test:
  commands:
    - $R -e "library('CHL26predictor')"  # [not win]
    - "\"%R%\" -e \"library('CHL26predictor')\""  # [win]

about:
  home: https
  license: MIT + file LICENSE
  summary: An R package for applying the classical Hodgkin lymphoma (cHL) 26 gene predictor
  license_family: MIT
