{% set version = '0.1.0' %}

package:
  name: r-tinyutils 
  version: {{ version }}

source:
  fn: tinyutils_{{ version }}.tar.gz
  url: https://github.com/tinyheero/tinyutils/archive/v{{ version }}.tar.gz

  md5: 27ef917879e17c27b1fdf746238a24ff

build:
  build: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base >=3.1.0
    - r-data.table >=1.9.4
    - r-ggplot2 >=1.0.0
    - r-dplyr >=0.4.3
    - r-som >=0.3.5
    - bioconductor-preprocesscore >=1.28.0
    - bioconductor-rsamtools >=1.20.5
    - bioconductor-genomicranges >=1.20.8

  run:
    - r-base >=3.1.0
    - r-data.table >=1.9.4
    - r-ggplot2 >=1.0.0
    - r-dplyr >=0.4.3
    - r-som >=0.3.5
    - bioconductor-preprocesscore >=1.28.0
    - bioconductor-rsamtools >=1.20.5
    - bioconductor-genomicranges >=1.20.8

test:
  commands:
    - $R -e "library('tinyutils')"  # [not win]
    - "\"%R%\" -e \"library('tinyutils')\""  # [win]

about:
  home: https://github.com/tinyheero/tinyutils
  license: GPL-2
  summary: R package with utility functions to help with data analysis
